-- ============================================
-- MIGRATION: Fix AI Video Asset Cascade Deletion
-- ============================================
-- Date: 2026-01-30
-- Description: Change ai_video_project_id on media_assets from ON DELETE CASCADE to ON DELETE SET NULL
-- Reason: To prevent project deletion from deleting associated media library assets.

BEGIN;

-- 1. Identify and drop the existing foreign key constraint
-- The standard name generated by Postgres is usually 'media_assets_ai_video_project_id_fkey'
ALTER TABLE media_assets 
DROP CONSTRAINT IF EXISTS media_assets_ai_video_project_id_fkey;

-- 2. Re-add the constraint with ON DELETE SET NULL
ALTER TABLE media_assets
ADD CONSTRAINT media_assets_ai_video_project_id_fkey 
FOREIGN KEY (ai_video_project_id) 
REFERENCES ai_video_projects(id) 
ON DELETE SET NULL;

-- 3. Add comment for documentation
COMMENT ON COLUMN media_assets.ai_video_project_id IS 'Link to ai_video_projects (SET NULL on delete to preserve assets)';

COMMIT;
