-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.chat_messages (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  draft_id uuid,
  user_id uuid,
  role text CHECK (role = ANY (ARRAY['user'::text, 'assistant'::text])),
  content text,
  created_at timestamp with time zone DEFAULT now(),
  session_id uuid,
  context text DEFAULT 'general'::text,
  content_type text DEFAULT 'text'::text,
  platform text DEFAULT 'general'::text,
  CONSTRAINT chat_messages_pkey PRIMARY KEY (id),
  CONSTRAINT chat_messages_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.content_drafts(id),
  CONSTRAINT chat_messages_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_messages_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.chat_sessions(id)
);
CREATE TABLE public.chat_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  context text DEFAULT 'general'::text,
  project_id uuid,
  draft_id uuid,
  title text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT chat_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT chat_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT chat_sessions_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT chat_sessions_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.content_drafts(id)
);
CREATE TABLE public.connected_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  getlate_profile_id uuid,
  getlate_account_id uuid,
  platform text CHECK (platform = ANY (ARRAY['instagram'::text, 'tiktok'::text, 'x'::text, 'linkedin'::text, 'facebook'::text, 'threads'::text, 'bluesky'::text, 'youtube'::text, 'pinterest'::text, 'late'::text])),
  profile_id text,
  profile_name text,
  access_token text,
  refresh_token text,
  expires_at timestamp with time zone,
  late_profile_id text,
  social_media_account_id text,
  profile_metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  connection_provider text DEFAULT 'late'::text CHECK (connection_provider = ANY (ARRAY['late'::text, 'native'::text])),
  platform_metadata jsonb DEFAULT '{}'::jsonb,
  CONSTRAINT connected_accounts_pkey PRIMARY KEY (id),
  CONSTRAINT connected_accounts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT connected_accounts_getlate_profile_id_fkey FOREIGN KEY (getlate_profile_id) REFERENCES public.getlate_profiles(id),
  CONSTRAINT connected_accounts_getlate_account_id_fkey FOREIGN KEY (getlate_account_id) REFERENCES public.getlate_accounts(id)
);
CREATE TABLE public.content_drafts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  project_id uuid,
  user_id uuid,
  platform text,
  text_content text,
  media_urls jsonb DEFAULT '[]'::jsonb,
  status text DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'scheduled'::text, 'posted'::text, 'failed'::text])),
  scheduled_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  media_type text,
  CONSTRAINT content_drafts_pkey PRIMARY KEY (id),
  CONSTRAINT content_drafts_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.projects(id),
  CONSTRAINT content_drafts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.content_goals (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  prompt_modifier_text text,
  CONSTRAINT content_goals_pkey PRIMARY KEY (id)
);
CREATE TABLE public.coupon_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  coupon_id uuid NOT NULL,
  user_id uuid NOT NULL,
  order_id uuid NOT NULL,
  discount_amount numeric NOT NULL,
  order_total numeric NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coupon_usage_pkey PRIMARY KEY (id),
  CONSTRAINT coupon_usage_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
  CONSTRAINT coupon_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT coupon_usage_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.coupons (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  code character varying NOT NULL UNIQUE,
  description text,
  discount_type character varying NOT NULL CHECK (discount_type::text = ANY (ARRAY['percentage'::character varying::text, 'fixed_amount'::character varying::text])),
  discount_value numeric NOT NULL CHECK (discount_value > 0::numeric),
  max_discount_amount numeric,
  min_order_amount numeric DEFAULT 0,
  usage_limit integer CHECK (usage_limit IS NULL OR usage_limit > 0),
  usage_count integer DEFAULT 0 CHECK (usage_count >= 0),
  usage_per_user integer DEFAULT 1 CHECK (usage_per_user > 0),
  start_date timestamp with time zone NOT NULL,
  end_date timestamp with time zone NOT NULL,
  applies_to_billing character varying NOT NULL DEFAULT 'yearly'::character varying CHECK (applies_to_billing::text = ANY (ARRAY['monthly'::character varying::text, 'yearly'::character varying::text, 'both'::character varying::text])),
  applies_to_plans ARRAY,
  is_active boolean DEFAULT true,
  created_by uuid,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT coupons_pkey PRIMARY KEY (id),
  CONSTRAINT coupons_created_by_fkey FOREIGN KEY (created_by) REFERENCES auth.users(id)
);
CREATE TABLE public.credit_transactions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  action_type text NOT NULL CHECK (action_type = ANY (ARRAY['PROJECT_CREATED'::text, 'POST_CREATED'::text, 'IMAGE_GENERATED'::text, 'VIDEO_GENERATED'::text, 'CREDIT_DEDUCTED'::text, 'CREDIT_PURCHASED'::text, 'POST_SCHEDULED'::text, 'POST_PUBLISHED'::text, 'AI_REFINEMENT'::text, 'VIDEO_PROCESSING'::text, 'TEXT_ONLY'::text, 'WITH_IMAGE'::text, 'WITH_VIDEO'::text])),
  credits_used integer DEFAULT 0,
  credits_remaining integer,
  resource_id uuid,
  resource_type text,
  platform text,
  metadata jsonb,
  response_data jsonb,
  created_at timestamp with time zone DEFAULT now(),
  order_id uuid,
  subscription_id uuid,
  source character varying DEFAULT 'purchase'::character varying CHECK (source::text = ANY (ARRAY['purchase'::character varying::text, 'subscription_renewal'::character varying::text, 'bonus'::character varying::text, 'refund'::character varying::text, 'admin_adjustment'::character varying::text])),
  CONSTRAINT credit_transactions_pkey PRIMARY KEY (id),
  CONSTRAINT credit_transactions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT credit_transactions_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id),
  CONSTRAINT credit_transactions_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.external_tasks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  step_id uuid NOT NULL,
  provider character varying NOT NULL CHECK (provider::text = ANY (ARRAY['aws_mediaconvert'::character varying, 'aws_transcribe'::character varying, 'openai'::character varying, 'gemini'::character varying]::text[])),
  external_job_id character varying NOT NULL,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['submitted'::character varying, 'running'::character varying, 'completed'::character varying, 'failed'::character varying]::text[])),
  last_polled_at timestamp with time zone,
  next_poll_at timestamp with time zone,
  poll_count integer DEFAULT 0,
  max_polls integer DEFAULT 100,
  timeout_at timestamp with time zone,
  hard_cap_at timestamp with time zone,
  poll_locked_until timestamp with time zone,
  poll_owner text,
  raw_response jsonb,
  output jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT external_tasks_pkey PRIMARY KEY (id),
  CONSTRAINT external_tasks_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT external_tasks_step_id_fkey FOREIGN KEY (step_id) REFERENCES public.job_steps(id)
);
CREATE TABLE public.files (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  key text,
  bucket text,
  mime text,
  size bigint,
  metadata jsonb,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT files_pkey PRIMARY KEY (id),
  CONSTRAINT files_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.framework_niches (
  framework_id uuid NOT NULL,
  niche_id uuid NOT NULL,
  override_prompt_text text,
  CONSTRAINT framework_niches_pkey PRIMARY KEY (framework_id, niche_id),
  CONSTRAINT framework_niches_framework_id_fkey FOREIGN KEY (framework_id) REFERENCES public.frameworks(id),
  CONSTRAINT framework_niches_niche_id_fkey FOREIGN KEY (niche_id) REFERENCES public.niches(id)
);
CREATE TABLE public.frameworks (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  title text NOT NULL,
  slug text UNIQUE,
  description text,
  icon_name text NOT NULL,
  goal_ids ARRAY DEFAULT '{}'::uuid[],
  base_prompt_text text,
  placeholders ARRAY DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT timezone('utc'::text, now()),
  CONSTRAINT frameworks_pkey PRIMARY KEY (id)
);
CREATE TABLE public.getlate_accounts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  account_name text,
  api_key text NOT NULL UNIQUE,
  client_id text,
  client_secret text,
  webhook_secret text,
  is_active boolean DEFAULT true,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT getlate_accounts_pkey PRIMARY KEY (id)
);
CREATE TABLE public.getlate_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  getlate_account_id uuid,
  late_profile_id text NOT NULL UNIQUE,
  profile_name text,
  description text,
  social_media_ids jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT getlate_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT getlate_profiles_getlate_account_id_fkey FOREIGN KEY (getlate_account_id) REFERENCES public.getlate_accounts(id)
);
CREATE TABLE public.global_stock_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  keyword character varying NOT NULL,
  s3_key text NOT NULL UNIQUE,
  provider character varying NOT NULL CHECK (provider::text = ANY (ARRAY['pexels'::character varying, 'pixabay'::character varying]::text[])),
  provider_id character varying NOT NULL,
  orientation character varying NOT NULL CHECK (orientation::text = ANY (ARRAY['landscape'::character varying, 'portrait'::character varying, 'square'::character varying]::text[])),
  duration integer,
  width integer,
  height integer,
  preview_url text,
  tags ARRAY DEFAULT '{}'::text[],
  author character varying,
  license character varying,
  usage_count integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT global_stock_assets_pkey PRIMARY KEY (id)
);
CREATE TABLE public.job_steps (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid NOT NULL,
  step_name character varying NOT NULL,
  step_order integer NOT NULL DEFAULT 0,
  status character varying NOT NULL CHECK (status::text = ANY (ARRAY['pending'::character varying, 'running'::character varying, 'waiting'::character varying, 'completed'::character varying, 'failed'::character varying, 'skipped'::character varying]::text[])),
  waiting_reason character varying,
  retry_count integer DEFAULT 0,
  max_retries integer DEFAULT 5,
  started_at timestamp with time zone,
  finished_at timestamp with time zone,
  last_checked_at timestamp with time zone,
  next_check_at timestamp with time zone,
  timeout_at timestamp with time zone,
  error_code character varying,
  error_message text,
  output jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT job_steps_pkey PRIMARY KEY (id),
  CONSTRAINT job_steps_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id)
);
CREATE TABLE public.jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_type text,
  payload jsonb,
  status text DEFAULT 'queued'::text,
  attempts integer DEFAULT 0,
  last_error text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT jobs_pkey PRIMARY KEY (id)
);
CREATE TABLE public.media_assets (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  job_id uuid,
  asset_type text NOT NULL CHECK (asset_type = ANY (ARRAY['image'::text, 'video'::text, 'audio'::text, 'document'::text])),
  source_type text NOT NULL DEFAULT 'uploaded'::text CHECK (source_type = ANY (ARRAY['uploaded'::text, 'ai_generated'::text, 'processed'::text])),
  origin text,
  storage_type text NOT NULL DEFAULT 's3'::text CHECK (storage_type = ANY (ARRAY['supabase'::text, 's3'::text, 'url'::text])),
  storage_bucket text NOT NULL,
  storage_key text NOT NULL,
  public_url text NOT NULL,
  thumbnail_url text,
  thumbnail_key text,
  file_size bigint,
  mime_type text,
  duration integer,
  width integer,
  height integer,
  checksum text,
  metadata jsonb DEFAULT '{}'::jsonb,
  project_id uuid,
  parent_asset_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT media_assets_pkey PRIMARY KEY (id),
  CONSTRAINT media_assets_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT media_assets_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT media_assets_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.video_factory_projects(id),
  CONSTRAINT media_assets_parent_asset_id_fkey FOREIGN KEY (parent_asset_id) REFERENCES public.media_assets(id)
);
CREATE TABLE public.monthly_usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  month date NOT NULL,
  projects_created integer DEFAULT 0,
  posts_created integer DEFAULT 0,
  scheduled_posts integer DEFAULT 0,
  images_generated integer DEFAULT 0,
  videos_generated integer DEFAULT 0,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT monthly_usage_pkey PRIMARY KEY (id),
  CONSTRAINT monthly_usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.niches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  name text NOT NULL,
  slug text UNIQUE,
  description text,
  CONSTRAINT niches_pkey PRIMARY KEY (id)
);
CREATE TABLE public.orders (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_number character varying NOT NULL UNIQUE,
  user_id uuid,
  plan_id uuid,
  plan_name character varying NOT NULL,
  plan_slug character varying NOT NULL,
  billing_cycle character varying NOT NULL CHECK (billing_cycle::text = ANY (ARRAY['monthly'::character varying::text, 'yearly'::character varying::text])),
  credits_amount integer NOT NULL CHECK (credits_amount > 0),
  subtotal numeric NOT NULL CHECK (subtotal >= 0::numeric),
  discount_amount numeric DEFAULT 0 CHECK (discount_amount >= 0::numeric),
  total_amount numeric NOT NULL CHECK (total_amount >= 0::numeric),
  currency character varying DEFAULT 'VND'::character varying,
  coupon_id uuid,
  coupon_code character varying,
  coupon_discount_type character varying,
  coupon_discount_value numeric,
  customer_name character varying,
  customer_email character varying NOT NULL,
  customer_phone character varying,
  vnpay_txn_ref character varying UNIQUE,
  vnpay_transaction_no character varying,
  vnpay_bank_code character varying,
  vnpay_bank_tran_no character varying,
  vnpay_card_type character varying,
  vnpay_pay_date character varying,
  vnpay_response_code character varying,
  vnpay_transaction_status character varying,
  vnpay_secure_hash character varying,
  vnpay_raw_response jsonb,
  onepay_txn_ref character varying UNIQUE,
  onepay_transaction_no character varying,
  onepay_response_code character varying,
  onepay_transaction_status character varying,
  onepay_raw_response jsonb,
  status character varying NOT NULL DEFAULT 'pending'::character varying CHECK (status::text = ANY (ARRAY['pending'::character varying::text, 'paid'::character varying::text, 'completed'::character varying::text, 'failed'::character varying::text, 'expired'::character varying::text, 'refunded'::character varying::text, 'partially_refunded'::character varying::text])),
  payment_method character varying DEFAULT 'vnpay'::character varying,
  credits_added boolean DEFAULT false,
  credits_added_at timestamp with time zone,
  refund_amount numeric DEFAULT 0,
  refund_requested_at timestamp with time zone,
  refund_completed_at timestamp with time zone,
  refund_reason text,
  refund_credits_deducted integer DEFAULT 0,
  previous_plan_slug character varying,
  previous_plan_remaining_value numeric,
  subscription_id uuid,
  created_at timestamp with time zone DEFAULT now(),
  paid_at timestamp with time zone,
  completed_at timestamp with time zone,
  expires_at timestamp with time zone,
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT orders_pkey PRIMARY KEY (id),
  CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT orders_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id),
  CONSTRAINT orders_coupon_id_fkey FOREIGN KEY (coupon_id) REFERENCES public.coupons(id),
  CONSTRAINT orders_subscription_id_fkey FOREIGN KEY (subscription_id) REFERENCES public.subscriptions(id)
);
CREATE TABLE public.payment_logs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  order_id uuid,
  event_type character varying NOT NULL,
  payload jsonb,
  error_message text,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT payment_logs_pkey PRIMARY KEY (id),
  CONSTRAINT payment_logs_order_id_fkey FOREIGN KEY (order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.plans (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  slug character varying NOT NULL UNIQUE,
  name character varying NOT NULL,
  description text,
  credits_monthly integer NOT NULL,
  credits_yearly integer NOT NULL,
  price_monthly numeric NOT NULL,
  price_yearly numeric NOT NULL,
  features jsonb DEFAULT '[]'::jsonb,
  max_profiles integer,
  max_posts_per_month integer,
  tier_level integer NOT NULL,
  is_active boolean DEFAULT true,
  is_visible boolean DEFAULT true,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT plans_pkey PRIMARY KEY (id)
);
CREATE TABLE public.processing_jobs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  job_type text NOT NULL CHECK (job_type = ANY (ARRAY['image_generation'::text, 'video_generation'::text, 'video_factory'::text, 'video_cut'::text, 'video_merge'::text, 'video_subtitle'::text, 'video_translate'::text, 'video_download'::text, 'video_transcode'::text, 'video_add_brolls'::text, 'video_add_music'::text, 'video_add_logo'::text, 'audio_extract'::text, 'audio_merge'::text, 'audio_transcribe'::text, 'file_upload'::text, 'file_optimize'::text])),
  status text NOT NULL DEFAULT 'queued'::text CHECK (status = ANY (ARRAY['queued'::text, 'processing'::text, 'completed'::text, 'failed'::text, 'cancelled'::text, 'abandoned'::text])),
  priority integer DEFAULT 0,
  input_data jsonb NOT NULL,
  output_data jsonb,
  error_message text,
  progress integer DEFAULT 0 CHECK (progress >= 0 AND progress <= 100),
  progress_message text,
  aws_mediaconvert_job_id text,
  estimated_completion_time timestamp with time zone,
  started_at timestamp with time zone,
  completed_at timestamp with time zone,
  last_progress_at timestamp with time zone,
  last_heartbeat_at timestamp with time zone,
  abandon_reason text,
  timeout_at timestamp with time zone,
  max_duration_sec integer DEFAULT 28800,
  project_id uuid,
  job_subtype text CHECK (job_subtype IS NULL OR (job_subtype = ANY (ARRAY['cut'::text, 'postprocess'::text]))),
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT processing_jobs_pkey PRIMARY KEY (id),
  CONSTRAINT processing_jobs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT processing_jobs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.video_factory_projects(id)
);
CREATE TABLE public.projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  name text NOT NULL,
  description text,
  source_type text DEFAULT 'prompt'::text,
  source_content text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT projects_pkey PRIMARY KEY (id),
  CONSTRAINT projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.scheduled_posts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  draft_id uuid,
  getlate_profile_id uuid,
  getlate_account_id uuid,
  platform text,
  scheduled_at timestamp with time zone,
  late_job_id text,
  status text DEFAULT 'scheduled'::text CHECK (status = ANY (ARRAY['scheduled'::text, 'publishing'::text, 'posted'::text, 'failed'::text, 'cancelled'::text])),
  post_url text,
  payload jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  connected_account_id uuid,
  CONSTRAINT scheduled_posts_pkey PRIMARY KEY (id),
  CONSTRAINT scheduled_posts_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT scheduled_posts_draft_id_fkey FOREIGN KEY (draft_id) REFERENCES public.content_drafts(id),
  CONSTRAINT scheduled_posts_getlate_profile_id_fkey FOREIGN KEY (getlate_profile_id) REFERENCES public.getlate_profiles(id),
  CONSTRAINT scheduled_posts_getlate_account_id_fkey FOREIGN KEY (getlate_account_id) REFERENCES public.getlate_accounts(id),
  CONSTRAINT scheduled_posts_connected_account_id_fkey FOREIGN KEY (connected_account_id) REFERENCES public.connected_accounts(id)
);
CREATE TABLE public.subscriptions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  lemonsqueezy_subscription_id text UNIQUE,
  lemonsqueezy_customer_id text,
  plan text NOT NULL CHECK (plan = ANY (ARRAY['creator'::text, 'creator_pro'::text, 'agency'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'cancelled'::text, 'past_due'::text, 'expired'::text])),
  current_period_start timestamp with time zone,
  current_period_end timestamp with time zone,
  cancel_at_period_end boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  plan_id uuid,
  billing_cycle character varying CHECK (billing_cycle::text = ANY (ARRAY['monthly'::character varying::text, 'yearly'::character varying::text])),
  credits_per_period integer DEFAULT 0,
  next_credit_date date,
  is_auto_renew boolean DEFAULT false,
  original_order_id uuid,
  CONSTRAINT subscriptions_pkey PRIMARY KEY (id),
  CONSTRAINT subscriptions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT subscriptions_plan_id_fkey FOREIGN KEY (plan_id) REFERENCES public.plans(id),
  CONSTRAINT subscriptions_original_order_id_fkey FOREIGN KEY (original_order_id) REFERENCES public.orders(id)
);
CREATE TABLE public.usage (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  credits_used integer DEFAULT 0,
  credits_purchased integer DEFAULT 0,
  period_start timestamp with time zone NOT NULL,
  period_end timestamp with time zone NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT usage_pkey PRIMARY KEY (id),
  CONSTRAINT usage_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id)
);
CREATE TABLE public.users (
  id uuid NOT NULL,
  name text,
  avatar_url text,
  plan text DEFAULT 'free'::text CHECK (plan = ANY (ARRAY['free'::text, 'creator'::text, 'creator_pro'::text, 'agency'::text])),
  lemonsqueezy_customer_id text,
  lemonsqueezy_subscription_id text,
  subscription_status text DEFAULT 'inactive'::text CHECK (subscription_status = ANY (ARRAY['active'::text, 'inactive'::text, 'cancelled'::text, 'past_due'::text, 'expired'::text])),
  subscription_ends_at timestamp with time zone,
  credits_balance integer DEFAULT 0,
  last_login_at timestamp with time zone,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  role text DEFAULT 'user'::text CHECK (role IS NULL OR (role = ANY (ARRAY['user'::text, 'admin'::text]))),
  current_plan_slug character varying DEFAULT 'free'::character varying,
  current_plan_id uuid,
  last_plan_purchase_at timestamp with time zone,
  next_credit_grant_at timestamp with time zone,
  CONSTRAINT users_pkey PRIMARY KEY (id),
  CONSTRAINT users_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id),
  CONSTRAINT users_current_plan_id_fkey FOREIGN KEY (current_plan_id) REFERENCES public.plans(id)
);
CREATE TABLE public.video_factory_audio_transcripts (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  audio_media_asset_id uuid NOT NULL UNIQUE,
  source_media_asset_id uuid,
  audio_s3_uri text NOT NULL,
  transcript jsonb,
  transcript_source text,
  translations jsonb DEFAULT '{}'::jsonb,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT video_factory_audio_transcripts_pkey PRIMARY KEY (id),
  CONSTRAINT video_factory_audio_transcripts_audio_media_asset_id_fkey FOREIGN KEY (audio_media_asset_id) REFERENCES public.media_assets(id),
  CONSTRAINT video_factory_audio_transcripts_source_media_asset_id_fkey FOREIGN KEY (source_media_asset_id) REFERENCES public.media_assets(id)
);
CREATE TABLE public.video_factory_outputs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  cut_job_id uuid NOT NULL,
  postprocess_job_id uuid NOT NULL UNIQUE,
  project_id uuid,
  final_video_url text,
  final_video_key text,
  thumbnail_url text,
  thumbnail_key text,
  postprod_config jsonb,
  selected_clip_keys ARRAY,
  status text NOT NULL DEFAULT 'processing'::text CHECK (status = ANY (ARRAY['processing'::text, 'completed'::text, 'failed'::text])),
  duration_seconds integer,
  file_size bigint,
  metadata jsonb DEFAULT '{}'::jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT video_factory_outputs_pkey PRIMARY KEY (id),
  CONSTRAINT video_factory_outputs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT video_factory_outputs_cut_job_id_fkey FOREIGN KEY (cut_job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT video_factory_outputs_postprocess_job_id_fkey FOREIGN KEY (postprocess_job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT video_factory_outputs_project_id_fkey FOREIGN KEY (project_id) REFERENCES public.video_factory_projects(id)
);
CREATE TABLE public.video_factory_projects (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid,
  job_id uuid UNIQUE,
  project_name text,
  source_type text NOT NULL CHECK (source_type = ANY (ARRAY['youtube'::text, 'upload'::text])),
  source_url text NOT NULL,
  source_thumbnail_url text,
  source_duration_seconds integer,
  source_media_asset_id uuid,
  audio_transcript_id uuid,
  audio_media_asset_id uuid,
  transcript jsonb,
  transcript_source text,
  cut_config jsonb,
  postprod_config jsonb,
  output_clips jsonb,
  final_video_url text,
  status text NOT NULL DEFAULT 'processing'::text CHECK (status = ANY (ARRAY['draft'::text, 'cutting'::text, 'ready'::text, 'processing_post'::text, 'completed'::text, 'processing'::text, 'failed'::text])),
  current_cut_job_id uuid,
  current_processing_job_id uuid,
  input_snapshot jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT video_factory_projects_pkey PRIMARY KEY (id),
  CONSTRAINT video_factory_projects_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id),
  CONSTRAINT video_factory_projects_audio_transcript_id_fkey FOREIGN KEY (audio_transcript_id) REFERENCES public.video_factory_audio_transcripts(id),
  CONSTRAINT video_factory_projects_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT video_factory_projects_source_media_asset_id_fkey FOREIGN KEY (source_media_asset_id) REFERENCES public.media_assets(id),
  CONSTRAINT video_factory_projects_audio_media_asset_id_fkey FOREIGN KEY (audio_media_asset_id) REFERENCES public.media_assets(id),
  CONSTRAINT video_factory_projects_current_cut_job_id_fkey FOREIGN KEY (current_cut_job_id) REFERENCES public.processing_jobs(id),
  CONSTRAINT video_factory_projects_current_processing_job_id_fkey FOREIGN KEY (current_processing_job_id) REFERENCES public.processing_jobs(id)
);
CREATE TABLE public.video_processing_configs (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  job_id uuid,
  operation_type text NOT NULL CHECK (operation_type = ANY (ARRAY['cut'::text, 'merge'::text, 'subtitle'::text, 'translate'::text, 'transcode'::text, 'add_brolls'::text, 'add_music'::text, 'add_logo'::text])),
  config jsonb NOT NULL,
  created_at timestamp with time zone DEFAULT now(),
  CONSTRAINT video_processing_configs_pkey PRIMARY KEY (id),
  CONSTRAINT video_processing_configs_job_id_fkey FOREIGN KEY (job_id) REFERENCES public.processing_jobs(id)
);