"use client";

import Header from "@/components/shared/header";
import Footer from "@/components/shared/footer";
import { useTranslations } from "next-intl";

export default function TermsPage() {
  const t = useTranslations("TermsPage"); // Assuming you might want to localize this title later, but content is English for now per request

  return (
    <div className="min-h-screen bg-background flex flex-col">
      <Header />
      
      <main className="flex-1 container mx-auto px-4 py-12 max-w-4xl">
        <h1 className="text-3xl font-bold mb-8">Terms of Service</h1>
        

        <div className="prose prose-slate dark:prose-invert max-w-none space-y-6">
          <p className="text-muted-foreground">Last updated: {new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}</p>

          <section>
            <h2 className="text-xl font-semibold mb-3">1. Acceptance of Terms</h2>
            <p>
              Welcome to Maiovo ("the Service"). By accessing and using our AI-powered content creation and automation platform, 
              you agree to be bound by these Terms of Service. If you do not agree to these terms, please do not use our Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">2. Description of Service</h2>
            <p>
              Maiovo provides an all-in-one marketing tool that allows users to create, transform, schedule, and post content 
              across multiple social media platforms (including but not limited to Instagram, TikTok, YouTube, Facebook, and LinkedIn) 
              using Artificial Intelligence.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">3. User Accounts and Security</h2>
            <p>
              To access certain features, you must register for an account. You are responsible for maintaining the confidentiality 
              of your account credentials and for all activities that occur under your account. You agree to notify us immediately 
              of any unauthorized use of your account.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">4. Content and AI Generation</h2>
            <ul className="list-disc pl-5 space-y-2">
              <li><strong>Ownership:</strong> You retain ownership of any content (text, images, videos) you upload ("Input Content"). 
              Subject to applicable laws, you also own the rights to the content generated by the Service ("Generated Content").</li>
              <li><strong>License to Us:</strong> By using the Service, you grant us a license to process, host, and display your Input Content 
              and Generated Content solely for the purpose of providing and improving the Service.</li>
              <li><strong>AI Disclaimer:</strong> You acknowledge that the Service uses AI technologies (which may include third-party models like ChatGPT, ElevenLabs, etc.) 
              to generate content. AI generation can be unpredictable, and you are responsible for reviewing and verifying all Generated Content 
              before publishing it.</li>
            </ul>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">5. Social Media Platform Rules</h2>
            <p>
              When using Maiovo to post to third-party platforms (e.g., YouTube, TikTok, Instagram), you agree to comply with 
              the Terms of Service and Community Guidelines of those respective platforms. Maiovo is not responsible for any 
              account suspensions or content removals by third-party platforms resulting from your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">6. Payment and Subscription</h2>
            <p>
              Maiovo offers various subscription plans (Free, Creator, Creator Pro, Agency). specific limits on AI generation credits, 
              storage, and connected accounts apply to each plan. All fees are non-refundable unless otherwise stated.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">7. Limitation of Liability</h2>
            <p>
              To the fullest extent permitted by law, Maiovo shall not be liable for any indirect, incidental, special, consequential, 
              or punitive damages, including but not limited to loss of profits, data, or goodwill, arising out of your use of the Service.
            </p>
          </section>

          <section>
            <h2 className="text-xl font-semibold mb-3">8. Contact Us</h2>
            <p>
              If you have any questions about these Terms, please contact us at support@maiovo.com.
            </p>
          </section>
        </div>
      </main>

      <Footer />
    </div>
  );
}
