import { NextRequest } from "next/server";
import { requireAuth } from "@/lib/auth";
import { success, fail } from "@/lib/response";
import { lemonClient } from "@/lib/payments/lemonsqueezy";
import { getUserSubscription, updateSubscriptionStatus, updateUserPlan } from "@/lib/services/db/users";

/**
 * GET /api/billing/subscription
 * Get subscription management information
 */
export async function GET(req: NextRequest) {
  try {
    const user = await requireAuth(req);
    if (!user) return fail("Unauthorized", 401);

    // Get user's subscription via service layer
    const subscription = await getUserSubscription(user.id);

    if (!subscription) {
      return success({
        hasSubscription: false,
        subscription: null,
        customerPortalUrl: null
      });
    }

    // Get customer portal URL from LemonSqueezy
    let customerPortalUrl = null;
    try {
      if (subscription.lemonsqueezy_customer_id) {
        // This would typically be generated by LemonSqueezy
        customerPortalUrl = `https://app.lemonsqueezy.com/my-orders/${subscription.lemonsqueezy_customer_id}`;
      }
    } catch (error) {
      console.error("Error getting customer portal URL:", error);
    }

    return success({
      hasSubscription: true,
      subscription,
      customerPortalUrl
    });

  } catch (err: any) {
    console.error("GET /api/billing/subscription error:", err);
    return fail(err.message || "Server error", 500);
  }
}

/**
 * DELETE /api/billing/subscription
 * Cancel subscription
 */
export async function DELETE(req: NextRequest) {
  try {
    const user = await requireAuth(req);
    if (!user) return fail("Unauthorized", 401);

    // Get user's subscription via service layer
    const subscription = await getUserSubscription(user.id);

    if (!subscription) {
      return fail("No active subscription found", 404);
    }

    if (!subscription.lemonsqueezy_subscription_id) {
      return fail("Invalid subscription", 400);
    }

    // Cancel subscription via LemonSqueezy
    try {
      await lemonClient.cancelSubscription(subscription.lemonsqueezy_subscription_id);
    } catch (error) {
      console.error("Error cancelling subscription:", error);
      return fail("Failed to cancel subscription", 500);
    }

    // Update subscription status via service layer
    const updatedSubscription = await updateSubscriptionStatus(subscription.id, {
      status: 'cancelled',
      cancel_at_period_end: true
    });

    if (!updatedSubscription) {
      return fail("Failed to update subscription status", 500);
    }

    // Update user's plan back to free via service layer
    const planUpdated = await updateUserPlan(user.id, {
      plan: 'free',
      subscription_status: 'cancelled'
    });

    if (!planUpdated) {
      console.warn("Failed to update user plan, but subscription was cancelled");
    }

    return success({
      message: "Subscription cancelled successfully",
      subscription: {
        ...subscription,
        status: 'cancelled',
        cancel_at_period_end: true
      }
    });

  } catch (err: any) {
    console.error("DELETE /api/billing/subscription error:", err);
    return fail(err.message || "Server error", 500);
  }
}
